### ISSUE TITLE
Retry is package as a development version

### ISSUE THREAD

**Issue by rgreinho** [invl/retry#2]
The retry package on the PyPI is marked as a development version (denoted by ``.dev83`` at the end of the name). The actual name of the package should be ``retry-0.9.0-py2.py3-none-any.whl``

One way to repackage it properly is the following:
```bash
git tag -a 0.9.0 -m "v0.9.0" d56f5f9
git checkout -b v0.9.0 0.9.0
python3 setup.py sdist bdist_wheel
```

**Comment by invl** [comment]
Thanks, I didn't know annotated tag was required, seems not mentioned in pbr documentation.
