### ISSUE TITLE
requirement of decorator>=3.4.2,<4.0.0

### ISSUE THREAD

**Issue by citterio** [invl/retry#6]
What is the issue with decorator v. 4.0.0 and above? I have some systems with decorator 4.0.2 installed as dependency by some application (I don't know which one) so I'd prefer to keep that newer version if possible.

**Comment by infecto** [comment]
4.0.0 is supposedly backwards compatible but I have not tested it against retry. Would be nice if we could remove this requirements though.

**Comment by levi-rs** [comment]
Any chance we get get the latest stable package pushed to PyPI?
