### ISSUE TITLE
Running in loop depletes the retry count even when no Exception was raised

### ISSUE THREAD

**Issue by tobszarny** [invl/retry#63]
Running in loop depletes the retry count even when no Exception was raised

```python
@retry(tries=5)
def foo(i):
    print(i)


if __name__ == '__main__':
    for i in range(10):
        foo(i)
```

The example above will stop at 5th call from the loop

**Comment by rcatalinas-reinfer** [comment]
I was curious to test this issue as well and for me with `Python 3.10.6` works as intended (looping+printing from 0 to 9). Maybe with Python 3 works just fine?

**Comment by Kshitij68** [comment]
I used `Python 3.10.9` and did not find the issue. 
@tobszarny Could you mention the python version on your system?

**Comment by tobszarny** [comment]
I've changed my system since then. Can't replicate. Seems all good.
